DEFAULT_SHIP = {
    "LOA": 323.6,
    "Beam": 37.2,
    "Draft": 8.2,
    "AFW": 1250.0,
    "ALW": 6120.0,
    "ALC": 1200.0,
}

if "certificates_db" not in st.session_state:
    st.session_state.certificates_db = pd.DataFrame([
        {
            "cert_id": "CERT-HMPE-2025-01",
            "manufacturer": "Samson Rope",
            "material": "HMPE",
            "diameter_mm": 64,
            "mbl_tons": 105.0,
            "standard": "MEG4 / DNV",
            "issue_date": "2025-01-15",
        },
        {
            "cert_id": "CERT-HMPE-2025-02",
            "manufacturer": "Katradis",
            "material": "HMPE",
            "diameter_mm": 64,
            "mbl_tons": 105.0,
            "standard": "MEG4 / LRS",
            "issue_date": "2025-02-10",
        },
        {
            "cert_id": "CERT-TAIL-2025-A1",
            "manufacturer": "Lankhorst",
            "material": "Polyester",
            "diameter_mm": 72,
            "mbl_tons": 100.0,
            "standard": "MEG4",
            "issue_date": "2025-03-01",
        },
    ])

if "mooring_stations" not in st.session_state:
    st.session_state.mooring_stations = {
        "Forward Station (Prua)": pd.DataFrame([
            {
                "winch_id": "W1",
                "winch_type": "Split Drum",
                "chock_id": "C1",
                "chock_x_m": 150.0,
                "chock_y_m": 2.0,
                "chock_z_m": 12.0,
                "brake_holding_tons": 84.0,
            },
            {
                "winch_id": "W2",
                "winch_type": "Split Drum",
                "chock_id": "C2",
                "chock_x_m": 150.0,
                "chock_y_m": -2.0,
                "chock_z_m": 12.0,
                "brake_holding_tons": 84.0,
            },
            {
                "winch_id": "W3",
                "winch_type": "Single Drum",
                "chock_id": "C3",
                "chock_x_m": 138.0,
                "chock_y_m": 18.0,
                "chock_z_m": 10.0,
                "brake_holding_tons": 84.0,
            },
            {
                "winch_id": "W4",
                "winch_type": "Single Drum",
                "chock_id": "C4",
                "chock_x_m": 110.0,
                "chock_y_m": 18.0,
                "chock_z_m": 8.0,
                "brake_holding_tons": 84.0,
            },
        ]),
        "Aft Station (Poppa)": pd.DataFrame([
            {
                "winch_id": "W5",
                "winch_type": "Single Drum",
                "chock_id": "C5",
                "chock_x_m": -110.0,
                "chock_y_m": 18.0,
                "chock_z_m": 8.0,
                "brake_holding_tons": 84.0,
            },
            {
                "winch_id": "W6",
                "winch_type": "Split Drum",
                "chock_id": "C6",
                "chock_x_m": -138.0,
                "chock_y_m": 18.0,
                "chock_z_m": 10.0,
                "brake_holding_tons": 84.0,
            },
            {
                "winch_id": "W7",
                "winch_type": "Split Drum",
                "chock_id": "C7",
                "chock_x_m": -150.0,
                "chock_y_m": 0.0,
                "chock_z_m": 12.0,
                "brake_holding_tons": 84.0,
            },
        ]),
    }

if "lines_inventory" not in st.session_state:
    st.session_state.lines_inventory = pd.DataFrame([
        {
            "line_id": "1",
            "line_name": "Head Line 1",
            "line_type": "Head",
            "station_id": "Forward Station (Prua)",
            "winch_id": "W1",
            "cert_id": "CERT-HMPE-2025-01",
            "chock_x_m": 150.0,
            "chock_y_m": 2.0,
            "chock_z_m": 12.0,
            "material": "HMPE",
            "diameter_mm": 64,
            "E_modulus_GPa": 120,
            "mbl_tons": 105.0,
            "tail_length_m": 11.0,
            "tail_diameter_mm": 72,
            "tail_E_modulus_GPa": 6,
            "tail_mbl_tons": 100.0,
            "bollard_id": "B1",
        },
        {
            "line_id": "2",
            "line_name": "Head Line 2",
            "line_type": "Head",
            "station_id": "Forward Station (Prua)",
            "winch_id": "W2",
            "cert_id": "CERT-HMPE-2025-01",
            "chock_x_m": 150.0,
            "chock_y_m": -2.0,
            "chock_z_m": 12.0,
            "material": "HMPE",
            "diameter_mm": 64,
            "E_modulus_GPa": 120,
            "mbl_tons": 105.0,
            "tail_length_m": 11.0,
            "tail_diameter_mm": 72,
            "tail_E_modulus_GPa": 6,
            "tail_mbl_tons": 100.0,
            "bollard_id": "B1",
        },
        {
            "line_id": "3",
            "line_name": "Fwd Breast 1",
            "line_type": "Fwd Breast",
            "station_id": "Forward Station (Prua)",
            "winch_id": "W3",
            "cert_id": "CERT-HMPE-2025-02",
            "chock_x_m": 138.0,
            "chock_y_m": 18.0,
            "chock_z_m": 10.0,
            "material": "HMPE",
            "diameter_mm": 64,
            "E_modulus_GPa": 120,
            "mbl_tons": 105.0,
            "tail_length_m": 11.0,
            "tail_diameter_mm": 72,
            "tail_E_modulus_GPa": 6,
            "tail_mbl_tons": 100.0,
            "bollard_id": "B2",
        },
        {
            "line_id": "4",
            "line_name": "Fwd Spring 1",
            "line_type": "Fwd Spring",
            "station_id": "Forward Station (Prua)",
            "winch_id": "W4",
            "cert_id": "CERT-HMPE-2025-02",
            "chock_x_m": 110.0,
            "chock_y_m": 18.0,
            "chock_z_m": 8.0,
            "material": "HMPE",
            "diameter_mm": 64,
            "E_modulus_GPa": 120,
            "mbl_tons": 105.0,
            "tail_length_m": 0.0,
            "tail_diameter_mm": 0,
            "tail_E_modulus_GPa": 0,
            "tail_mbl_tons": 0,
            "bollard_id": "B3",
        },
        {
            "line_id": "5",
            "line_name": "Aft Spring 1",
            "line_type": "Aft Spring",
            "station_id": "Aft Station (Poppa)",
            "winch_id": "W5",
            "cert_id": "CERT-HMPE-2025-01",
            "chock_x_m": -110.0,
            "chock_y_m": 18.0,
            "chock_z_m": 8.0,
            "material": "HMPE",
            "diameter_mm": 64,
            "E_modulus_GPa": 120,
            "mbl_tons": 105.0,
            "tail_length_m": 0.0,
            "tail_diameter_mm": 0,
            "tail_E_modulus_GPa": 0,
            "tail_mbl_tons": 0,
            "bollard_id": "B4",
        },
        {
            "line_id": "6",
            "line_name": "Aft Breast 1",
            "line_type": "Aft Breast",
            "station_id": "Aft Station (Poppa)",
            "winch_id": "W6",
            "cert_id": "CERT-HMPE-2025-02",
            "chock_x_m": -138.0,
            "chock_y_m": 18.0,
            "chock_z_m": 10.0,
            "material": "HMPE",
            "diameter_mm": 64,
            "E_modulus_GPa": 120,
            "mbl_tons": 105.0,
            "tail_length_m": 11.0,
            "tail_diameter_mm": 72,
            "tail_E_modulus_GPa": 6,
            "tail_mbl_tons": 100.0,
            "bollard_id": "B5",
        },
        {
            "line_id": "7",
            "line_name": "Stern Line 1",
            "line_type": "Stern",
            "station_id": "Aft Station (Poppa)",
            "winch_id": "W7",
            "cert_id": "CERT-HMPE-2025-02",
            "chock_x_m": -150.0,
            "chock_y_m": 0.0,
            "chock_z_m": 12.0,
            "material": "HMPE",
            "diameter_mm": 64,
            "E_modulus_GPa": 120,
            "mbl_tons": 105.0,
            "tail_length_m": 11.0,
            "tail_diameter_mm": 72,
            "tail_E_modulus_GPa": 6,
            "tail_mbl_tons": 100.0,
            "bollard_id": "B5",
        },
    ])

def_bollards = [
    {
        "bollard_id": "B1",
        "Posizione": "Prua",
        "Dist_Inclinata_m": 15.0,
        "Pendenza_deg": 0.0,
        "Dist_Orizzontale_m": 15.0,
        "X_Coordinata_m": 125.8,
        "Y_Coordinata_m": 25.0,
        "Z_Altezza_m": -3.0,
        "SWL_Bitta_t": 150,
        "Stato": "Attivo",
    },
    {
        "bollard_id": "B2",
        "Posizione": "Prua",
        "Dist_Inclinata_m": 25.0,
        "Pendenza_deg": 0.0,
        "Dist_Orizzontale_m": 25.0,
        "X_Coordinata_m": 115.8,
        "Y_Coordinata_m": 25.0,
        "Z_Altezza_m": -3.0,
        "SWL_Bitta_t": 150,
        "Stato": "Attivo",
    },
    {
        "bollard_id": "B3",
        "Posizione": "Prua",
        "Dist_Inclinata_m": 60.0,
        "Pendenza_deg": 0.0,
        "Dist_Orizzontale_m": 60.0,
        "X_Coordinata_m": 80.8,
        "Y_Coordinata_m": 25.0,
        "Z_Altezza_m": -3.0,
        "SWL_Bitta_t": 100,
        "Stato": "Attivo",
    },
    {
        "bollard_id": "B4",
        "Posizione": "Poppa",
        "Dist_Inclinata_m": 65.0,
        "Pendenza_deg": 0.0,
        "Dist_Orizzontale_m": 65.0,
        "X_Coordinata_m": -82.8,
        "Y_Coordinata_m": 25.0,
        "Z_Altezza_m": -3.0,
        "SWL_Bitta_t": 100,
        "Stato": "Attivo",
    },
    {
        "bollard_id": "B5",
        "Posizione": "Poppa",
        "Dist_Inclinata_m": 10.0,
        "Pendenza_deg": 0.0,
        "Dist_Orizzontale_m": 10.0,
        "X_Coordinata_m": -137.8,
        "Y_Coordinata_m": 25.0,
        "Z_Altezza_m": -3.0,
        "SWL_Bitta_t": 150,
        "Stato": "Attivo",
    },
]

if "ports_bollards" not in st.session_state:
    st.session_state.ports_bollards = {
        "Long Beach Cruise Terminal": pd.DataFrame(def_bollards),
        "Mazatlan Pier 4/5": pd.DataFrame(def_bollards),
        "Mazatlan Pier 2/3": pd.DataFrame(def_bollards),
        "La Paz": pd.DataFrame(def_bollards),
        "Ensenada Pier #2": pd.DataFrame(def_bollards),
        "Puerto Vallarta Pier #1": pd.DataFrame(def_bollards),
        "Puerto Vallarta Pier #3": pd.DataFrame(def_bollards),
    }

if "port_headings" not in st.session_state:
    st.session_state.port_headings = {
        "Long Beach Cruise Terminal": 135.0,
        "Mazatlan Pier 4/5": 315.0,
        "Mazatlan Pier 2/3": 135.0,
        "La Paz": 180.0,
        "Ensenada Pier #2": 220.0,
        "Puerto Vallarta Pier #1": 0.0,
        "Puerto Vallarta Pier #3": 0.0,
    }

init_db(st.session_state.lines_inventory)
