"""FWD mooring equipment catalogue transcribed from drawing 006242A2C010105_01_101832731607(1).
Only source-identification data is stored here; no plan or ship coordinates are invented.
"""

DRAWING_ID = "006242A2C010105_01_101832731607(1)"

FWD_EQUIPMENT = [
    {"item":1,"piece_number":"YA/752A","type":"WINCH","quantity":1,"description":"COMBINED WINDLASS/MOORING WINCH PORT"},
    {"item":2,"piece_number":"YA/752B","type":"WINCH","quantity":1,"description":"COMBINED WINDLASS/MOORING WINCH STBD"},
    {"item":3,"piece_number":"YD/752D","type":"OTHER","quantity":1,"description":"ELECTRIC MOTOR BRAKE FOR DECK WINDLASS BRAKE"},
    {"item":4,"piece_number":"YD/752AA","type":"OTHER","quantity":1,"description":"CHAIN STOPPER FOR CHAIN D/L PORT"},
    {"item":5,"piece_number":"YD/752BB","type":"OTHER","quantity":1,"description":"CHAIN STOPPER FOR CHAIN D/L STBD"},
    {"item":6,"piece_number":"YV/753A","type":"WINCH","quantity":1,"description":"TWO DRUMS WINCH AND ONE WARPING HEAD"},
    {"item":7,"piece_number":"YV/753B","type":"WINCH","quantity":1,"description":"TWO DRUMS WINCH AND ONE WARPING HEAD"},
    {"item":8,"piece_number":"YD/752AB","type":"REMOTE_CONTROL","quantity":1,"description":"REMOTE CONTROL STANDS WINDLASS PORT"},
    {"item":9,"piece_number":"YD/752AC","type":"REMOTE_CONTROL","quantity":1,"description":"REMOTE CONTROL STANDS WINDLASS STBD"},
    {"item":10,"piece_number":"YD/753AA","type":"REMOTE_CONTROL","quantity":1,"description":"REMOTE CONTROL STANDS MOORING WINCH PORT"},
    {"item":11,"piece_number":"YD/753AB","type":"REMOTE_CONTROL","quantity":1,"description":"REMOTE CONTROL STANDS MOORING WINCH STBD"},
    {"item":12,"piece_number":"OF/050BI","type":"BOLLARD","quantity":8,"description":"DOUBLE BOLLARD ND 500"},
    {"item":13,"piece_number":"OF/002FS","type":"OTHER","quantity":8,"description":"BOLLARDS FOUNDATION PLATE"},
    {"item":14,"piece_number":"OF/052PC","type":"CHOCK","quantity":1,"description":"PANAMA CHOCK 400x270"},
    {"item":15,"piece_number":"OF/053PC","type":"CHOCK","quantity":1,"description":"PANAMA CHOCK 400x270"},
    {"item":16,"piece_number":"OF/054PC","type":"CHOCK","quantity":1,"description":"PANAMA CHOCK 400x270"},
    {"item":17,"piece_number":"OF/055PC","type":"CHOCK","quantity":1,"description":"PANAMA CHOCK 400x270"},
    {"item":18,"piece_number":"OF/056PC","type":"CHOCK","quantity":1,"description":"PANAMA CHOCK 400x270"},
    {"item":19,"piece_number":"OF/057PC","type":"CHOCK","quantity":1,"description":"PANAMA CHOCK 400x270"},
    {"item":20,"piece_number":"OF/058PC","type":"FAIRLEAD","quantity":1,"description":"FOUR ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
    {"item":21,"piece_number":"OF/059PC","type":"FAIRLEAD","quantity":1,"description":"FOUR ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
    {"item":22,"piece_number":"OF/060PC","type":"FAIRLEAD","quantity":1,"description":"FOUR ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
    {"item":23,"piece_number":"OF/061PC","type":"FAIRLEAD","quantity":1,"description":"FOUR ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
    {"item":24,"piece_number":"OF/062PC","type":"FAIRLEAD","quantity":1,"description":"THREE ROLLERS UNIVERSAL FAIRLEAD; NOTE 2"},
    {"item":25,"piece_number":"OF/063PC","type":"FAIRLEAD","quantity":1,"description":"THREE ROLLERS UNIVERSAL FAIRLEAD; NOTE 2"},
    {"item":26,"piece_number":"OF/064PC","type":"FAIRLEAD","quantity":1,"description":"THREE ROLLERS UNIVERSAL FAIRLEAD; NOTE 2"},
    {"item":27,"piece_number":"OF/065PC","type":"FAIRLEAD","quantity":1,"description":"THREE ROLLERS UNIVERSAL FAIRLEAD; NOTE 2"},
    {"item":28,"piece_number":"OF/066PC","type":"FAIRLEAD","quantity":1,"description":"THREE ROLLERS UNIVERSAL FAIRLEAD; NOTE 2"},
    {"item":29,"piece_number":"OF/067PC","type":"FAIRLEAD","quantity":1,"description":"THREE ROLLERS UNIVERSAL FAIRLEAD; NOTE 2"},
    {"item":30,"piece_number":"OF/068PC","type":"FAIRLEAD","quantity":1,"description":"SEVEN ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
    {"item":31,"piece_number":"OF/069PC","type":"FAIRLEAD","quantity":1,"description":"SEVEN ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
    {"item":32,"piece_number":"OF/070RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
    {"item":33,"piece_number":"OF/071RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":34,"piece_number":"OF/072RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
    {"item":35,"piece_number":"OF/073RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":36,"piece_number":"OF/074RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
    {"item":37,"piece_number":"OF/075RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":38,"piece_number":"OF/076RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
    {"item":39,"piece_number":"OF/077RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":40,"piece_number":"OF/079RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":41,"piece_number":"OF/080RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
    {"item":42,"piece_number":"OF/081RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":43,"piece_number":"OF/082RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
    {"item":44,"piece_number":"OF/083RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":45,"piece_number":"OF/084RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
    {"item":46,"piece_number":"OF/090RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
    {"item":47,"piece_number":"OF/091RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":49,"piece_number":"OF/078GK","type":"OTHER","quantity":4,"description":"CAGE FOR MOORING ROPES Type D (Bolted to Deck)"},
    {"item":50,"piece_number":"OF/085DV","type":"OTHER","quantity":1,"description":"PLATFORM FOR BRAKE OPERATION"},
    {"item":51,"piece_number":"OF/091DV","type":"OTHER","quantity":1,"description":"FLOOR BOARD FOR OBSERVATION MOORING AREA PORT"},
    {"item":52,"piece_number":"OF/092DV","type":"OTHER","quantity":1,"description":"FLOOR BOARD FOR OBSERVATION MOORING AREA STBD"},
    {"item":53,"piece_number":"OF/093DV","type":"OTHER","quantity":1,"description":"HAWSE PIPE COVER STBD"},
    {"item":54,"piece_number":"OF/094DV","type":"OTHER","quantity":1,"description":"HAWSE PIPE COVER PORT"},
    {"item":55,"piece_number":"OF/088DV + OF/089DV","type":"OTHER","quantity":4,"description":"HANDRAIL PROTECTION FOR HAWSE PIPE (2+2)"},
    {"item":56,"piece_number":"OF/095DV + OF/096DV","type":"OTHER","quantity":4,"description":"WINCHMAN VERTICAL PROTECTION (2+2), H=1900"},
    {"item":57,"piece_number":"OF/191DV","type":"OTHER","quantity":1,"description":"FLOOR BOARD FOR OBSERVATION MOORING AREA STBD"},
    {"item":58,"piece_number":"OF/192DV","type":"OTHER","quantity":1,"description":"FLOOR BOARD FOR OBSERVATION MOORING AREA PORT"},
    {"item":59,"piece_number":"OF/092RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
    {"item":60,"piece_number":"OF/093RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
]

DRAWING_NOTES = [
    "Fairleads use the drawing notes indicated as Note 1 / Note 2; the exact note wording remains tied to the source drawing.",
    "Mooring fittings marked SWL 852 kN in the supplied drawing notes.",
    "Vertical guide rollers and fairleads are to be used with one mooring rope at a time according to the drawing notes.",
]
