"""Equipment catalogue transcribed from the supplied Panorama mooring drawing.
Coordinates are deliberately not included; they must come from the drawing/calibration.
"""
DRAWING_ID = "006242A2C010105_01_101832731607(1)"

AFT_EQUIPMENT = [
{"piece_number":"YA/753C","type":"WINCH","quantity":1,"description":"TWO DRUMS WINCH AND ONE WARPING HEAD"},
{"piece_number":"YA/753D","type":"WINCH","quantity":1,"description":"TWO DRUMS WINCH AND TWO WARPING HEAD"},
{"piece_number":"YA/753E","type":"WINCH","quantity":1,"description":"TWO DRUMS WINCH AND ONE WARPING HEAD"},
{"piece_number":"YA/753F","type":"WINCH","quantity":1,"description":"TWO DRUMS WINCH AND TWO WARPING HEAD"},
{"piece_number":"YD/753DB","type":"REMOTE_CONTROL","quantity":1,"description":"REMOTE CONTROL STANDS MOORING WINCH STBD"},
{"piece_number":"YD/753DA","type":"REMOTE_CONTROL","quantity":1,"description":"REMOTE CONTROL STANDS MOORING WINCH PORT"},
{"piece_number":"OF/097DV","type":"OTHER","quantity":1,"description":"WINCHMAN VERTICAL PROTECTION STBD"},
{"piece_number":"OF/098DV","type":"OTHER","quantity":1,"description":"WINCHMAN VERTICAL PROTECTION PORT"},
{"piece_number":"OF/023GK","type":"OTHER","quantity":1,"description":"CAGE FOR MOORING ROPES TYPE D"},
{"piece_number":"OF/001BI","type":"BOLLARD","quantity":8,"description":"DOUBLE BOLLARD ND 500"},
{"piece_number":"OF/001FS","type":"OTHER","quantity":8,"description":"BOLLARDS FOUNDATION PLATE"},
{"piece_number":"OF/003PC","type":"CHOCK","quantity":1,"description":"PANAMA CHOCK 400x270"},
{"piece_number":"OF/004PC","type":"CHOCK","quantity":1,"description":"PANAMA CHOCK 400x270"},
{"piece_number":"OF/005PC","type":"FAIRLEAD","quantity":1,"description":"SEVEN ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/006PC","type":"FAIRLEAD","quantity":1,"description":"SEVEN ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/007PC","type":"FAIRLEAD","quantity":1,"description":"SEVEN ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/008PC","type":"FAIRLEAD","quantity":1,"description":"SEVEN ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/009PC","type":"FAIRLEAD","quantity":1,"description":"SEVEN ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/028PC","type":"FAIRLEAD","quantity":1,"description":"FOUR ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/029PC","type":"FAIRLEAD","quantity":1,"description":"FOUR ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/011PC","type":"FAIRLEAD","quantity":1,"description":"FIVE ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/012PC","type":"FAIRLEAD","quantity":1,"description":"FIVE ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/013PC","type":"FAIRLEAD","quantity":1,"description":"FIVE ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/014PC","type":"FAIRLEAD","quantity":1,"description":"FIVE ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/025PC","type":"FAIRLEAD","quantity":1,"description":"FIVE ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/026PC","type":"FAIRLEAD","quantity":1,"description":"FIVE ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/015PC","type":"FAIRLEAD","quantity":1,"description":"FOUR ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/016PC","type":"FAIRLEAD","quantity":1,"description":"FOUR ROLLERS UNIVERSAL FAIRLEAD; NOTE 1"},
{"piece_number":"OF/021RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
{"piece_number":"OF/022RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
{"piece_number":"OF/027PC","type":"EXTERNAL_ROLLER","quantity":6,"description":"EXTERNAL SHIP ROLLER ND 220"},
{"piece_number":"WA/753D","type":"REMOTE_CONTROL","quantity":2,"description":"REMOTE CONTROL STAND SUPPORT"},
{"piece_number":"OF/023RO","type":"DOUBLE_VERTICAL_GUIDE","quantity":1,"description":"DOUBLE VERTICAL GUIDE ROLLER ND 350 STBD"},
{"piece_number":"OF/024RO","type":"DOUBLE_VERTICAL_GUIDE","quantity":1,"description":"DOUBLE VERTICAL GUIDE ROLLER ND 350 STBD"},
{"piece_number":"OF/025RO","type":"DOUBLE_VERTICAL_GUIDE","quantity":1,"description":"DOUBLE VERTICAL GUIDE ROLLER ND 350 PORT"},
{"piece_number":"OF/026RO","type":"DOUBLE_VERTICAL_GUIDE","quantity":1,"description":"DOUBLE VERTICAL GUIDE ROLLER ND 350 PORT"},
{"piece_number":"OF/076RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
{"piece_number":"OF/077RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
{"piece_number":"OF/079RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
{"piece_number":"OF/080RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
{"piece_number":"OF/082RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
{"piece_number":"OF/083RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
{"piece_number":"OF/090RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
{"piece_number":"OF/091RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 STBD"},
{"piece_number":"OF/092RO","type":"VERTICAL_GUIDE","quantity":1,"description":"VERTICAL GUIDE ROLLER ND 350 PORT"},
]

DRAWING_NOTES = [
"Fairleads: lower rope protection half pipe 168.3 x 10.97 mm.",
"Where Note 2 applies, upper rope protection half pipe 114.3 x 8.56 mm is also required.",
"Mooring fittings marked SWL 852 kN.",
"Specified vertical guide rollers/fairleads are to be used with one mooring rope at a time.",
"Rope leading must comply with the arrangement; final fitting position is confirmed after lead-line inspection.",
]
